target("debug_viewer")
    add_files("debug_viewer.cpp")
    add_deps("virtual_mesh", "gpu_rands")
    add_deps("lc-runtime", "lc-core", "lc-dsl", "lc-gui", "lc-backends-dummy")
    set_rundir("$(projectdir)")
target_end()

target("test_heap")
    add_files("test_heap.cpp")
    add_deps("mesh_simplify")
target_end()

target("test_simplify")
    add_files("test_simplify.cpp")
    add_deps("mesh_simplify", "gpu_rands")
    add_deps("stb-image")
    add_deps("lc-runtime", "lc-core", "lc-dsl", "lc-gui", "lc-backends-dummy")
    set_rundir("$(projectdir)")
target_end()

target("test_mesh_struct")
    add_files("test_mesh_struct.cpp")
    add_deps("mesh_simplify", "gpu_rands")
    add_deps("stb-image")
    add_deps("lc-runtime", "lc-core", "lc-dsl", "lc-gui", "lc-backends-dummy")
    set_rundir("$(projectdir)")
target_end()

target("test_partition")
    add_files("test_partition.cpp")
    add_deps("virtual_mesh", "gpu_rands")
    add_deps("lc-runtime", "lc-core", "lc-dsl", "lc-gui", "lc-backends-dummy")
    set_rundir("$(projectdir)")
target_end()

target("trans_builtin_code")
    add_files("trans_builtin_code.cpp")
    add_deps("lc-runtime", "lc-core")
    set_rundir("$(projectdir)")
target_end()