add_requires("assimp", {build = true, configs = {shared = true}})
-- add_requires("meshoptimizer", {build = true, configs = {shared = true}})
add_requires("nlohmann_json")
-- add_requires("coost")

target("test_assimp")
    add_files("test_assimp.cpp")
    add_deps("lc-core")
    add_packages("assimp")
    set_rundir("$(projectdir)")
target_end()

target("test_opt")
    add_files("test_opt.cpp")
    add_deps("lc-runtime", "lc-core", "lc-dsl", "lc-gui")
    add_deps("gpu_rands")
    add_deps("stb-image")
    add_deps("meshoptimizer")
    add_packages("assimp")
    set_rundir("$(projectdir)")
target_end()

target("test_raster_func")
    add_files("test_raster_func.cpp")
    add_deps("lc-runtime", "lc-core", "lc-dsl", "lc-gui")
    add_deps("gpu_rands")
    add_deps("stb-image")
    add_deps("meshoptimizer")
    add_packages("assimp", "nlohmann_json")
    set_rundir("$(projectdir)")
target_end()